language: node_js

node_js:
  - stable
  - v4
  - v5
  - v6
  - v7

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - secure: VJilnnPkpe2sgWHFHZde25Cql9CnEZibvO0o9ESI3WfikO6y8LMPmTGMbRY26rrgzwLR5mqhFJXWSLkx48jq7HETz0TTN8V8frA74kt9kE6sEU/cfM8oJMKJvkRVK3iWU0A/UkMOOaTFPyDuZXwMjaHUMuaV/5bvUpyY1mXnxOs=

script:
  - npm run lint
  - npm test

after_script:
  - npm run cover
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
